FROM hypriot/rpi-node:latest

#  GPIO 사용을 위한 필수 라이브러리 (bcm2835) 설치
RUN mkdir -p /opt/down
WORKDIR /opt/down
RUN wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.56.tar.gz
RUN tar zxvf bcm2835-1.56.tar.gz
WORKDIR /opt/down/bcm2835-1.56
RUN ./configure
RUN make


# 앱 디렉터리 생성
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# 앱 의존성 설치
COPY package.json /usr/src/app/
RUN npm install


# 앱 소스 추가
COPY . /usr/src/app

CMD [ "npm", "start" ]
